// STRUCTURE LOCKED — do not edit this file.
// To change colours/fonts edit src/site.theme.ts.
// To change text/images edit src/site.content.ts and src/site.images.ts.
import { motion } from "motion/react";
import { Calendar, ArrowRight } from "lucide-react";
import { ImageWithFallback } from "./figma/ImageWithFallback";
import { config } from "../config";

const bp = config.blogPage;
const posts = bp.posts;

export function BlogPage() {
  return (
    <div style={{ fontFamily: config.brand.fonts.sans }}>
      {/* Hero */}
      <section className="py-20" style={{ backgroundColor: config.brand.primary }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center">
            <span className="inline-block px-4 py-1.5 rounded-full mb-4" style={{ backgroundColor: "rgba(199,32,42,0.18)", color: "#FFEAF0", fontSize: "13px", fontWeight: 600, letterSpacing: "1px", textTransform: "uppercase" }}>
              {bp.badge}
            </span>
            <h1 className="m-0 mb-4 text-white" style={{ fontFamily: config.brand.fonts.serif, fontSize: "clamp(32px, 4vw, 50px)", fontWeight: 700 }}>
              {bp.heading}
            </h1>
            <p className="m-0 mx-auto" style={{ fontSize: "16px", color: "#FFFFFF", maxWidth: "520px", lineHeight: 1.7 }}>
              {bp.intro}
            </p>
          </motion.div>
        </div>
      </section>

      {/* Blog Grid */}
      <section style={{ backgroundColor: config.brand.background }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          {/* Featured Post */}
          <motion.article
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-12 grid grid-cols-1 lg:grid-cols-2 gap-0 rounded-2xl overflow-hidden group cursor-pointer"
            style={{ backgroundColor: config.brand.white, border: `1px solid ${config.brand.border}`, boxShadow: "0 4px 20px rgba(0,0,0,0.04)" }}
          >
            <div className="h-[280px] lg:h-auto overflow-hidden">
              <ImageWithFallback src={posts[0].image} alt={posts[0].title} className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105" />
            </div>
            <div className="p-8 lg:p-10 flex flex-col justify-center">
              <span className="inline-block self-start px-3 py-1 rounded-full mb-4" style={{ fontSize: "12px", fontWeight: 600, backgroundColor: "rgba(199,32,42,0.12)", color: "#B11F2A" }}>
                {posts[0].tag}
              </span>
              <h2 className="m-0 mb-3" style={{ fontFamily: config.brand.fonts.serif, fontSize: "24px", fontWeight: 700, color: config.brand.light, lineHeight: 1.3 }}>
                {posts[0].title}
              </h2>
              <p className="mb-4" style={{ fontSize: "14px", color: config.brand.secondary, lineHeight: 1.7 }}>{posts[0].excerpt}</p>
              <div className="flex items-center gap-2" style={{ fontSize: "13px", color: config.brand.muted }}>
                <Calendar size={14} />
                {posts[0].date}
              </div>
            </div>
          </motion.article>

          {/* Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {posts.slice(1).map((post, i) => (
              <motion.article
                key={post.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.08 }}
                className="rounded-2xl overflow-hidden group cursor-pointer transition-all duration-200"
                style={{ backgroundColor: config.brand.white, border: `1px solid ${config.brand.border}` }}
                onMouseEnter={(e) => { e.currentTarget.style.boxShadow = "0 8px 30px rgba(0,0,0,0.06)"; e.currentTarget.style.transform = "translateY(-2px)"; }}
                onMouseLeave={(e) => { e.currentTarget.style.boxShadow = "none"; e.currentTarget.style.transform = "translateY(0)"; }}
              >
                <div className="h-[200px] overflow-hidden">
                  <ImageWithFallback src={post.image} alt={post.title} className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105" />
                </div>
                <div className="p-6">
                  <div className="flex items-center justify-between mb-3">
                    <span className="px-3 py-1 rounded-full" style={{ fontSize: "11px", fontWeight: 600, backgroundColor: "rgba(199,32,42,0.12)", color: "#B11F2A" }}>
                      {post.tag}
                    </span>
                    <span className="flex items-center gap-1" style={{ fontSize: "12px", color: config.brand.muted }}>
                      <Calendar size={12} />
                      {post.date}
                    </span>
                  </div>
                  <h3 className="m-0 mb-2" style={{ fontSize: "16px", fontWeight: 700, color: config.brand.light, lineHeight: 1.3 }}>
                    {post.title}
                  </h3>
                  <p className="m-0 mb-4" style={{ fontSize: "13px", color: config.brand.secondary, lineHeight: 1.6 }}>{post.excerpt}</p>
                  <span className="inline-flex items-center gap-1" style={{ fontSize: "13px", fontWeight: 600, color: config.brand.primary }}>
                    {bp.readMoreLink} <ArrowRight size={14} />
                  </span>
                </div>
              </motion.article>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
