// STRUCTURE LOCKED — do not edit this file.
// To change colours/fonts edit src/site.theme.ts.
// To change text/images edit src/site.content.ts and src/site.images.ts.
import { Link } from "react-router";
import { motion } from "motion/react";
import { Building2, Shield, Users, Phone, CheckCircle2, type LucideIcon } from "lucide-react";
import { config } from "../config";

const cp = config.commercialPage;

// Icons for trust features — order matches commercialPage.trustFeatures in site.content.ts
const commercialFeatureIcons: LucideIcon[] = [Building2, Shield, Users];

export function CommercialPage() {
  return (
    <div style={{ fontFamily: config.brand.fonts.sans }}>
      {/* Hero */}
      <section className="py-14 sm:py-20" style={{ backgroundColor: config.brand.primary }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="text-center">
            <span className="inline-block px-3 py-1 sm:px-4 sm:py-1.5 rounded-full mb-3 sm:mb-4" style={{ backgroundColor: "rgba(199,32,42,0.18)", border: "1px solid rgba(199,32,42,0.45)", color: "#FFEAF0", fontSize: "clamp(11px, 2.8vw, 15px)", fontWeight: 600, letterSpacing: "0.8px", textTransform: "uppercase" }}>
              {cp.badge}
            </span>
            <h1 className="m-0 mb-4 text-white" style={{ fontFamily: config.brand.fonts.serif, fontSize: "clamp(36px, 4.6vw, 58px)", fontWeight: 700, lineHeight: 1.15 }}>
              {cp.heading.split("\n").map((line, i) => (
                <span key={i}>{line}{i < cp.heading.split("\n").length - 1 && <br />}</span>
              ))}
            </h1>
            <p className="m-0 mx-auto" style={{ fontSize: "17px", color: "#FFFFFF", maxWidth: "640px", lineHeight: 1.7 }}>
              {cp.intro}
            </p>
          </motion.div>
        </div>
      </section>

      {/* Content */}
      <section style={{ backgroundColor: config.brand.background }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-14 sm:py-20">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-start">
            <motion.div initial={{ opacity: 0, x: -20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }}>
              <h2 className="m-0 mb-5" style={{ fontFamily: config.brand.fonts.serif, fontSize: "32px", fontWeight: 700, color: config.brand.light }}>
                {cp.subheading} <span style={{ color: config.brand.accent }}>{cp.subheadingAccent}</span>
              </h2>
              {cp.bodyParagraphs.map((para, i) => (
                <p key={i} className="mb-5" style={{ fontSize: "16px", color: config.brand.secondary, lineHeight: 1.8 }}>
                  {para}
                </p>
              ))}
            </motion.div>

            <motion.div initial={{ opacity: 0, x: 20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }}>
              <div className="p-8 rounded-2xl" style={{ backgroundColor: config.brand.white, border: `1px solid ${config.brand.border}` }}>
                <h3 className="m-0 mb-6" style={{ fontSize: "18px", fontWeight: 700, color: config.brand.light }}>
                  {cp.sectorsLabel}
                </h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {cp.sectors.map((sector) => (
                    <div key={sector} className="flex items-center gap-3">
                      <CheckCircle2 size={16} style={{ color: config.brand.accent }} className="flex-shrink-0" />
                      <span style={{ fontSize: "15px", color: config.brand.text }}>{sector}</span>
                    </div>
                  ))}
                </div>
              </div>
            </motion.div>
          </div>

          {/* Trust Features */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-16">
            {cp.trustFeatures.map((feat, i) => {
              const Icon = commercialFeatureIcons[i];
              return (
                <motion.div
                  key={feat.title}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1 }}
                  className="p-7 rounded-2xl text-center"
                  style={{ backgroundColor: config.brand.white, border: `1px solid ${config.brand.border}` }}
                >
                  <div className="w-14 h-14 rounded-2xl flex items-center justify-center mx-auto mb-5" style={{ backgroundColor: "rgba(199,32,42,0.10)" }}>
                    <Icon size={26} style={{ color: config.brand.accent }} />
                  </div>
                  <h4 className="m-0 mb-2" style={{ fontSize: "17px", fontWeight: 700, color: config.brand.light }}>{feat.title}</h4>
                  <p className="m-0" style={{ fontSize: "15px", color: config.brand.secondary, lineHeight: 1.6 }}>{feat.desc}</p>
                </motion.div>
              );
            })}
          </div>

          {/* CTA */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mt-16 text-center p-12 rounded-2xl"
            style={{ backgroundColor: config.brand.primary }}
          >
            <h3 className="m-0 mb-3" style={{ color: "#F4F8FF", fontFamily: config.brand.fonts.serif, fontSize: "28px", fontWeight: 700 }}>
              {cp.ctaHeading}
            </h3>
            <p className="m-0 mb-6 mx-auto" style={{ fontSize: "16px", color: "rgba(244,248,255,0.88)", maxWidth: "450px" }}>
              {cp.ctaBody}
            </p>
            <Link
              to="/contact"
              className="inline-flex items-center gap-2 px-7 py-3.5 no-underline rounded-xl transition-all duration-200 hover:scale-105"
              style={{ backgroundColor: config.brand.primary, color: "#FFFFFF", fontSize: "16px", fontWeight: 700 }}
            >
              <Phone size={18} />
              {cp.ctaBtn}
            </Link>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
