// STRUCTURE LOCKED — do not edit this file.
// To change colours/fonts edit src/site.theme.ts.
// To change text edit src/site.content.ts.
import { useState } from "react";
import { motion } from "motion/react";
import { Phone, Mail, MapPin, Clock, Send, CheckCircle } from "lucide-react";
import { config } from "../config";

const cp = config.contactPage;
const panelGradient = "linear-gradient(135deg, rgba(255,255,255,0.98) 0%, rgba(242,247,253,0.98) 100%)";

export function ContactPage() {
  const [formData, setFormData] = useState({ name: "", email: "", phone: "", service: "", message: "" });
  const [submitted, setSubmitted] = useState(false);
  const [submitError, setSubmitError] = useState("");
  const web3formsKey = (config.web3forms_key ?? "").trim();
  const hasWeb3FormsKey =
    web3formsKey.length > 0 &&
    !/REPLACE_WITH|YOUR_WEB3FORMS_ACCESS_KEY/i.test(web3formsKey);
  const fallbackEmail = (config.business.email ?? "").trim();
  const hasFallbackEmail = fallbackEmail.length > 0;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError("");

    try {
      if (hasWeb3FormsKey) {
        const response = await fetch("https://api.web3forms.com/submit", {
          method: "POST",
          headers: { "Content-Type": "application/json", Accept: "application/json" },
          body: JSON.stringify({
            access_key: web3formsKey,
            subject: `New Enquiry from ${config.business.name} Website`,
            ...formData,
          }),
        });
        if (!response.ok) throw new Error("Web3Forms submit failed");
      } else {
        if (!hasFallbackEmail) throw new Error("No email fallback configured");
        const subject = encodeURIComponent(`New Enquiry from ${config.business.name} Website`);
        const body = encodeURIComponent(
          [
            `Name: ${formData.name}`,
            `Email: ${formData.email}`,
            `Phone: ${formData.phone || "-"}`,
            `Service: ${formData.service || "-"}`,
            "",
            "Message:",
            formData.message,
          ].join("\n"),
        );
        window.location.href = `mailto:${fallbackEmail}?subject=${subject}&body=${body}`;
      }

      setSubmitted(true);
      setFormData({ name: "", email: "", phone: "", service: "", message: "" });
    } catch {
      setSubmitError("Couldn't send your enquiry online right now. Please call us and we'll help immediately.");
    }
  };

  const contactInfo = [
    { icon: Phone, label: "Phone (anytime)", value: config.business.phoneDisplay,       href: `tel:${config.business.phone}`       },
    { icon: Mail,  label: "Email",            value: config.business.email,              href: `mailto:${config.business.email}`     },
    { icon: MapPin,label: "Area",             value: config.business.location,           href: null                                  },
    { icon: Clock, label: "Hours",            value: config.business.hours,              href: null                                  },
  ];

  const inputStyle: React.CSSProperties = {
    fontSize: "17px",
    backgroundColor: config.brand.background,
    border: `1px solid ${config.brand.border}`,
    borderRadius: "12px",
    padding: "12px 16px",
    width: "100%",
    outline: "none",
    transition: "border-color 0.2s",
    fontFamily: config.brand.fonts.sans,
  };

  return (
    <div style={{ fontFamily: config.brand.fonts.sans }}>
      {/* Hero */}
      <section className="py-14 sm:py-20" style={{ backgroundColor: config.brand.primary }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center">
            <span className="inline-block px-3 py-1 sm:px-4 sm:py-1.5 rounded-full mb-3 sm:mb-4" style={{ backgroundColor: "rgba(199,32,42,0.18)", color: "#FFEAF0", fontSize: "clamp(11px, 2.8vw, 15px)", fontWeight: 600, letterSpacing: "0.8px", textTransform: "uppercase" }}>
              {cp.badge}
            </span>
            <h1 className="m-0 mb-4 text-white" style={{ fontFamily: config.brand.fonts.serif, fontSize: "clamp(36px, 4.6vw, 58px)", fontWeight: 700 }}>
              {cp.heading}
            </h1>
            <p className="m-0 mx-auto" style={{ fontSize: "17px", color: "#FFFFFF", maxWidth: "520px", lineHeight: 1.7 }}>
              {cp.intro}
            </p>
          </motion.div>
        </div>
      </section>

      {/* Content */}
      <section style={{ backgroundColor: config.brand.background }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-14 sm:py-20">
          <div className="grid grid-cols-1 lg:grid-cols-5 gap-12">
            {/* Contact Info */}
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="order-2 lg:order-1 lg:col-span-2"
            >
              <h2 className="m-0 mb-6" style={{ fontFamily: config.brand.fonts.serif, fontSize: "28px", fontWeight: 700, color: config.brand.light }}>
                {cp.getInTouchLabel}
              </h2>
              <div className="space-y-5">
                {contactInfo.map((item) => (
                  <div key={item.label} className="flex items-start gap-4">
                    <div className="w-11 h-11 rounded-xl flex items-center justify-center flex-shrink-0" style={{ backgroundColor: "rgba(199,32,42,0.10)" }}>
                      <item.icon size={20} style={{ color: config.brand.accent }} />
                    </div>
                    <div>
                      <p className="m-0 mb-0.5" style={{ fontSize: "14px", color: config.brand.muted, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.5px" }}>{item.label}</p>
                      {item.href ? (
                        <a href={item.href} className="no-underline hover:underline" style={{ fontSize: "16px", fontWeight: 600, color: config.brand.light }}>{item.value}</a>
                      ) : (
                        <p className="m-0" style={{ fontSize: "16px", fontWeight: 600, color: config.brand.light }}>{item.value}</p>
                      )}
                    </div>
                  </div>
                ))}
              </div>

              {/* Quick CTA */}
              <div
                className="mt-8 p-6 rounded-2xl"
                style={{
                  background: panelGradient,
                  border: `1px solid ${config.brand.border}`,
                }}
              >
                <h4 className="m-0 mb-2" style={{ fontSize: "17px", fontWeight: 700, color: config.brand.light }}>{cp.preferCallLabel}</h4>
                <p className="m-0 mb-4" style={{ fontSize: "15px", color: config.brand.secondary, lineHeight: 1.6 }}>
                  {cp.preferCallBody}
                </p>
                <a
                  href={`tel:${config.business.phone}`}
                  className="inline-flex items-center gap-2 px-5 py-3 no-underline rounded-xl transition-all duration-200 hover:scale-105"
                  style={{ backgroundColor: config.brand.primary, color: "#FFFFFF", fontSize: "15px", fontWeight: 700 }}
                >
                  <Phone size={16} />
                  {cp.callNowBtn}
                </a>
              </div>
            </motion.div>

            {/* Form */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="order-1 lg:order-2 lg:col-span-3"
            >
              <div className="p-8 sm:p-10 rounded-2xl" style={{ background: panelGradient, border: `1px solid ${config.brand.border}`, boxShadow: "0 4px 20px rgba(0,0,0,0.04)" }}>
                {submitted ? (
                  <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="text-center py-12">
                    <CheckCircle size={56} className="mx-auto mb-5" style={{ color: config.brand.success }} />
                    <h3 className="m-0 mb-3" style={{ fontSize: "24px", fontWeight: 700, color: config.brand.light }}>{cp.successHeading}</h3>
                    <p className="m-0" style={{ fontSize: "16px", color: config.brand.secondary, lineHeight: 1.7 }}>
                      {cp.successBody}
                    </p>
                  </motion.div>
                ) : (
                  <>
                    <h3 className="m-0 mb-1" style={{ fontSize: "20px", fontWeight: 700, color: config.brand.light }}>
                      {cp.formHeading}
                    </h3>
                    <p className="m-0 mb-8" style={{ fontSize: "15px", color: config.brand.secondary }}>
                      {cp.formIntro}
                    </p>
                    <form onSubmit={handleSubmit} className="space-y-5">
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                        <div>
                          <label className="block mb-2" style={{ fontSize: "15px", fontWeight: 600, color: config.brand.text }}>{cp.formLabels.name}</label>
                          <input
                            type="text"
                            required
                            value={formData.name}
                            onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                            placeholder={cp.formPlaceholders.name}
                            style={inputStyle}
                            onFocus={(e) => e.target.style.borderColor = config.brand.primary}
                            onBlur={(e) => e.target.style.borderColor = config.brand.border}
                          />
                        </div>
                        <div>
                          <label className="block mb-2" style={{ fontSize: "15px", fontWeight: 600, color: config.brand.text }}>{cp.formLabels.email}</label>
                          <input
                            type="email"
                            required
                            value={formData.email}
                            onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                            placeholder={cp.formPlaceholders.email}
                            style={inputStyle}
                            onFocus={(e) => e.target.style.borderColor = config.brand.primary}
                            onBlur={(e) => e.target.style.borderColor = config.brand.border}
                          />
                        </div>
                      </div>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                        <div>
                          <label className="block mb-2" style={{ fontSize: "15px", fontWeight: 600, color: config.brand.text }}>{cp.formLabels.phone}</label>
                          <input
                            type="tel"
                            value={formData.phone}
                            onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                            placeholder={cp.formPlaceholders.phone}
                            style={inputStyle}
                            onFocus={(e) => e.target.style.borderColor = config.brand.primary}
                            onBlur={(e) => e.target.style.borderColor = config.brand.border}
                          />
                        </div>
                        <div>
                          <label className="block mb-2" style={{ fontSize: "15px", fontWeight: 600, color: config.brand.text }}>{cp.formLabels.service}</label>
                          <select
                            value={formData.service}
                            onChange={(e) => setFormData({ ...formData, service: e.target.value })}
                            style={{ ...inputStyle, appearance: "auto" as any }}
                            onFocus={(e) => e.target.style.borderColor = config.brand.primary}
                            onBlur={(e) => e.target.style.borderColor = config.brand.border}
                          >
                            <option value="">{cp.formPlaceholders.service}</option>
                            {cp.serviceOptions.map((opt) => (
                              <option key={opt}>{opt}</option>
                            ))}
                          </select>
                        </div>
                      </div>
                      <div>
                        <label className="block mb-2" style={{ fontSize: "15px", fontWeight: 600, color: config.brand.text }}>{cp.formLabels.message}</label>
                        <textarea
                          required
                          rows={5}
                          value={formData.message}
                          onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                          placeholder={cp.formPlaceholders.message}
                          style={{ ...inputStyle, resize: "none" as any }}
                          onFocus={(e) => e.target.style.borderColor = config.brand.primary}
                          onBlur={(e) => e.target.style.borderColor = config.brand.border}
                        />
                      </div>
                      <button
                        type="submit"
                        className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-8 py-3.5 border-none cursor-pointer rounded-xl transition-all duration-200 hover:scale-105"
                        style={{ backgroundColor: config.brand.primary, color: "#FFFFFF", fontSize: "16px", fontWeight: 700, fontFamily: config.brand.fonts.sans }}
                      >
                        <Send size={16} />
                        {cp.sendBtn}
                      </button>
                      {submitError ? (
                        <p className="m-0" style={{ fontSize: "14px", color: "#B11F2A", lineHeight: 1.6 }}>
                          {submitError}
                        </p>
                      ) : null}
                    </form>
                  </>
                )}
              </div>
            </motion.div>
          </div>
        </div>
      </section>
    </div>
  );
}
