// STRUCTURE LOCKED — do not edit this file.
// To change colours/fonts edit src/site.theme.ts.
// To change text/images edit src/site.content.ts and src/site.images.ts.
import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { X } from "lucide-react";
import { ImageWithFallback } from "./figma/ImageWithFallback";
import { config } from "../config";

// Gallery items come from config with src already resolved
const galleryImages = config.galleryPage.items;
const categories = ["All", ...Array.from(new Set(galleryImages.map(i => i.category)))];
const gp = config.galleryPage;

export function GalleryPage() {
  const [activeCategory, setActiveCategory] = useState("All");
  const [lightboxIndex, setLightboxIndex] = useState<number | null>(null);

  const filtered = activeCategory === "All" ? galleryImages : galleryImages.filter(i => i.category === activeCategory);

  return (
    <div style={{ fontFamily: config.brand.fonts.sans }}>
      {/* Hero */}
      <section className="py-20" style={{ backgroundColor: config.brand.primary }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
            <span className="inline-block px-4 py-1.5 rounded-full mb-4" style={{ backgroundColor: "rgba(199,32,42,0.18)", color: "#FFEAF0", fontSize: "15px", fontWeight: 600, letterSpacing: "1px", textTransform: "uppercase" }}>
              {gp.badge}
            </span>
            <h1 className="m-0 mb-4 text-white" style={{ fontFamily: config.brand.fonts.serif, fontSize: "clamp(36px, 4.6vw, 58px)", fontWeight: 700, lineHeight: 1.15 }}>
              {gp.heading}
            </h1>
            <p className="m-0" style={{ fontSize: "17px", color: "#FFFFFF", maxWidth: "520px", lineHeight: 1.7 }}>
              {gp.intro}
            </p>
          </motion.div>
        </div>
      </section>

      {/* Gallery */}
      <section style={{ backgroundColor: config.brand.background }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          {/* Filters */}
          <div className="flex flex-wrap gap-2 mb-10">
            {categories.map(cat => (
              <button
                key={cat}
                onClick={() => setActiveCategory(cat)}
                className="px-5 py-2.5 rounded-full border-none cursor-pointer transition-all duration-200"
                style={{
                  fontSize: "15px",
                  fontWeight: 700,
                  backgroundColor: activeCategory === cat ? config.brand.primary : config.brand.white,
                  color: activeCategory === cat ? "#FFFFFF" : config.brand.text,
                  border: activeCategory === cat ? "1px solid rgba(255,255,255,0.28)" : `1px solid ${config.brand.primaryAlpha30}`,
                  boxShadow: activeCategory === cat ? "none" : "0 1px 3px rgba(0,0,0,0.2)",
                }}
                onMouseEnter={(e) => {
                  if (activeCategory !== cat) {
                    e.currentTarget.style.backgroundColor = "rgba(26,62,115,0.12)";
                    e.currentTarget.style.borderColor = "rgba(26,62,115,0.45)";
                  }
                }}
                onMouseLeave={(e) => {
                  if (activeCategory !== cat) {
                    e.currentTarget.style.backgroundColor = config.brand.white;
                    e.currentTarget.style.borderColor = config.brand.primaryAlpha30;
                  }
                }}
              >
                {cat}
              </button>
            ))}
          </div>

          {/* Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {filtered.map((image, i) => (
              <motion.div
                key={image.src}
                layout
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                transition={{ duration: 0.3 }}
                className="relative group cursor-pointer rounded-2xl overflow-hidden"
                style={{ boxShadow: "0 4px 20px rgba(0,0,0,0.08)" }}
                onClick={() => setLightboxIndex(i)}
              >
                <ImageWithFallback src={image.src} alt={image.caption} className="w-full h-[260px] object-cover transition-transform duration-500 group-hover:scale-110" />
                <div className="absolute inset-0 flex items-end p-5 transition-opacity duration-300 opacity-0 group-hover:opacity-100" style={{ background: config.brand.galleryOverlay }}>
                  <div>
                    <p className="m-0 text-white" style={{ fontSize: "16px", fontWeight: 600 }}>{image.caption}</p>
                    <p className="m-0" style={{ fontSize: "14px", color: config.brand.light }}>{image.category}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Lightbox */}
      <AnimatePresence>
        {lightboxIndex !== null && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4"
            style={{ backgroundColor: "rgba(0,0,0,0.9)" }}
            onClick={() => setLightboxIndex(null)}
          >
            <button
              onClick={() => setLightboxIndex(null)}
              className="absolute top-6 right-6 w-10 h-10 rounded-full flex items-center justify-center border-none cursor-pointer"
              style={{ backgroundColor: "rgba(255,255,255,0.1)", color: "white" }}
            >
              <X size={20} />
            </button>
            <motion.div initial={{ scale: 0.9 }} animate={{ scale: 1 }} exit={{ scale: 0.9 }}>
              <ImageWithFallback
                src={filtered[lightboxIndex].src}
                alt={filtered[lightboxIndex].caption}
                className="max-w-full max-h-[80vh] rounded-xl object-contain"
              />
              <p className="text-center mt-4 text-white" style={{ fontSize: "17px", fontWeight: 600 }}>
                {filtered[lightboxIndex].caption}
              </p>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
