// STRUCTURE LOCKED — do not edit this file.
// To change colours/fonts edit src/site.theme.ts.
// To change text/images edit src/site.content.ts and src/site.images.ts.
import { Link } from "react-router";
import { motion } from "motion/react";
import {
  Phone,
  ArrowRight,
  ExternalLink,
  Hammer,
  PaintBucket,
  Bath,
  Grid3X3,
  Wrench,
  Home,
  Star,
  Clock,
  Award,
  Users,
  Shield,
  CheckCircle2,
  type LucideIcon,
} from "lucide-react";
import GoogleIcon from "@mui/icons-material/Google";
import { ImageWithFallback } from "./figma/ImageWithFallback";
import { config } from "../config";

const heroImg    = config.images.hero;
const kitchenImg = config.images.whyUs;
const teamImg    = config.images.team;

// Icon maps — add more icons here if needed
const serviceIconMap: Record<string, LucideIcon> = {
  hammer: Hammer, paintBucket: PaintBucket, bath: Bath,
  grid: Grid3X3, wrench: Wrench, home: Home,
};
const featureIconMap: Record<string, LucideIcon> = {
  award: Award, clock: Clock, shield: Shield, users: Users,
};

// Resolve icon components from config string names
const services     = config.services.map(s => ({ ...s, Icon: serviceIconMap[s.icon] ?? Hammer }));
const features     = config.features.map(f => ({ ...f, Icon: featureIconMap[f.icon] ?? Award  }));
const stats        = config.stats;
const testimonials = config.testimonials.slice(0, 3);
const hp           = config.homePage;
const googleReviewsUrl = config.reviewLinks.google;

export function HomePage() {
  return (
    <div style={{ fontFamily: config.brand.fonts.sans }}>
      {/* Hero Section */}
      <section className="relative min-h-[85vh] flex items-center overflow-hidden">
        <div className="absolute inset-0">
          <ImageWithFallback src={heroImg} alt="Modern construction" className="w-full h-full object-cover" />
          <div className="absolute inset-0" style={{ background: config.brand.heroGradient }} />
          <div
            className="absolute inset-0"
            style={{
              background:
                "linear-gradient(90deg, rgba(14,39,72,0.84) 0%, rgba(14,39,72,0.6) 36%, rgba(14,39,72,0.2) 68%, rgba(14,39,72,0.02) 100%)",
            }}
          />
        </div>
        <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 w-full">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="max-w-2xl"
          >
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full mb-6" style={{ backgroundColor: "rgba(199,32,42,0.2)", border: "1px solid rgba(199,32,42,0.45)" }}>
              <div className="w-2 h-2 rounded-full" style={{ backgroundColor: config.brand.accent }} />
              <span style={{ fontSize: "15px", color: "#FFEAF0", fontWeight: 500 }}>{config.hero.badge}</span>
            </div>
            <h1 className="m-0 mb-5 text-white" style={{ fontFamily: config.brand.fonts.serif, fontSize: "clamp(42px, 5.4vw, 68px)", fontWeight: 700, lineHeight: 1.1, letterSpacing: "-1px", textShadow: "0 2px 14px rgba(0,0,0,0.35)" }}>
              {config.hero.headline} <br />
              <span style={{ color: "#FFFFFF" }}>{config.hero.headlineAccent}</span>
            </h1>
            <p className="mb-8" style={{ fontSize: "18px", color: "#F1F5F9", lineHeight: 1.7, maxWidth: "520px", textShadow: "0 1px 10px rgba(0,0,0,0.3)" }}>
              {config.hero.subheading}
            </p>
            <div className="flex flex-wrap gap-4">
              <Link
                to="/contact"
                className="inline-flex items-center gap-2 px-7 py-3.5 no-underline rounded-xl transition-all duration-200 hover:scale-105"
                style={{ backgroundColor: config.brand.primary, color: "#FFFFFF", fontSize: "16px", fontWeight: 700 }}
              >
                <Phone size={18} />
                {hp.heroCtas.primary}
              </Link>
              <Link
                to="/services"
                className="inline-flex items-center gap-2 px-7 py-3.5 no-underline rounded-xl transition-all duration-200 hover:scale-105"
                style={{ backgroundColor: "rgba(255,255,255,0.1)", backdropFilter: "blur(8px)", border: "1px solid rgba(255,255,255,0.2)", color: "white", fontSize: "16px", fontWeight: 600 }}
              >
                {hp.heroCtas.secondary}
                <ArrowRight size={18} />
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Stats Bar */}
      <section style={{ backgroundColor: config.brand.primary }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
            {stats.map((stat) => (
              <motion.div
                key={stat.label}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5 }}
              >
                <p className="m-0" style={{ color: "#F4F8FF", fontSize: "clamp(28px, 4vw, 40px)", fontWeight: 800, lineHeight: 1 }}>{stat.value}</p>
                <p className="m-0 mt-1" style={{ fontSize: "15px", color: "rgba(244,248,255,0.88)", fontWeight: 600 }}>{stat.label}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Services Section */}
      <section style={{ backgroundColor: config.brand.background }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <span className="inline-block px-4 py-1.5 rounded-full mb-4" style={{ backgroundColor: "rgba(199,32,42,0.1)", border: "1px solid rgba(199,32,42,0.28)", color: "#B11F2A", fontSize: "15px", fontWeight: 600, letterSpacing: "1px", textTransform: "uppercase" }}>
              {hp.servicesSection.badge}
            </span>
            <h2 className="m-0 mb-4" style={{ fontFamily: config.brand.fonts.serif, fontSize: "clamp(32px, 3.9vw, 46px)", fontWeight: 700, color: config.brand.light, letterSpacing: "-0.5px" }}>
              {hp.servicesSection.heading}
            </h2>
            <p className="m-0 mx-auto" style={{ fontSize: "17px", color: config.brand.secondary, maxWidth: "580px", lineHeight: 1.7 }}>
              {hp.servicesSection.body}
            </p>
          </motion.div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {services.map((service, i) => (
              <motion.div
                key={service.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.08 }}
              >
                <Link
                  to="/services"
                  className="block p-7 rounded-2xl no-underline transition-all duration-300 group"
                  style={{ backgroundColor: config.brand.white, border: `1px solid ${config.brand.border}` }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.boxShadow = "0 8px 30px rgba(0,0,0,0.08)";
                    e.currentTarget.style.borderColor = config.brand.primaryAlpha20;
                    e.currentTarget.style.transform = "translateY(-2px)";
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.boxShadow = "none";
                    e.currentTarget.style.borderColor = config.brand.border;
                    e.currentTarget.style.transform = "translateY(0)";
                  }}
                >
                  <div className="w-12 h-12 rounded-xl flex items-center justify-center mb-5" style={{ backgroundColor: "rgba(199,32,42,0.10)" }}>
                    <service.Icon size={22} style={{ color: config.brand.accent }} />
                  </div>
                  <h3 className="m-0 mb-2" style={{ fontSize: "17px", fontWeight: 700, color: config.brand.light }}>{service.title}</h3>
                  <p className="m-0" style={{ fontSize: "15px", color: config.brand.secondary, lineHeight: 1.6 }}>{service.summary}</p>
                </Link>
              </motion.div>
            ))}
          </div>

          <div className="text-center mt-10">
            <Link
              to="/services"
              className="inline-flex items-center gap-2 no-underline transition-colors hover:gap-3"
              style={{ fontSize: "16px", fontWeight: 600, color: config.brand.primary }}
            >
              {hp.servicesSection.viewAllLink} <ArrowRight size={16} />
            </Link>
          </div>
        </div>
      </section>

      {/* Why Choose Us */}
      <section style={{ backgroundColor: config.brand.white }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <span className="inline-block px-4 py-1.5 rounded-full mb-4" style={{ backgroundColor: "rgba(199,32,42,0.1)", border: "1px solid rgba(199,32,42,0.28)", color: "#B11F2A", fontSize: "15px", fontWeight: 600, letterSpacing: "1px", textTransform: "uppercase" }}>
                Why {config.business.name}
              </span>
              <h2 className="m-0 mb-5" style={{ fontFamily: config.brand.fonts.serif, fontSize: "clamp(32px, 3.9vw, 44px)", fontWeight: 700, color: config.brand.light, lineHeight: 1.2 }}>
                {hp.whyUsSection.heading} <span style={{ color: config.brand.accent }}>{hp.whyUsSection.headingAccent}</span>
              </h2>
              <p className="mb-8" style={{ fontSize: "16px", color: config.brand.secondary, lineHeight: 1.8 }}>
                {hp.whyUsSection.body}
              </p>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                {features.map((feature, i) => (
                  <motion.div
                    key={feature.title}
                    initial={{ opacity: 0, y: 15 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.4, delay: i * 0.1 }}
                    className="flex gap-3"
                  >
                    <div className="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0" style={{ backgroundColor: "rgba(199,32,42,0.10)" }}>
                      <feature.Icon size={18} style={{ color: config.brand.accent }} />
                    </div>
                    <div>
                      <h4 className="m-0 mb-1" style={{ fontSize: "15px", fontWeight: 700, color: config.brand.light }}>{feature.title}</h4>
                      <p className="m-0" style={{ fontSize: "15px", color: config.brand.secondary, lineHeight: 1.6 }}>{feature.desc}</p>
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="relative"
            >
              <div className="rounded-2xl overflow-hidden" style={{ boxShadow: "0 20px 60px rgba(0,0,0,0.12)" }}>
                <ImageWithFallback src={kitchenImg} alt="Modern kitchen" className="w-full h-[450px] object-cover" />
              </div>
              <div
                className="absolute -bottom-6 -left-6 px-6 py-4 rounded-xl hidden lg:block"
                style={{ backgroundColor: config.brand.dark, boxShadow: "0 8px 30px rgba(0,0,0,0.2)" }}
              >
                <div className="flex items-center gap-3">
                  <div className="flex">
                    {[...Array(5)].map((_, i) => (
                      <Star key={i} size={16} fill={config.brand.starYellow} color={config.brand.starYellow} />
                    ))}
                  </div>
                  <span style={{ fontSize: "15px", color: "#F4F8FF", fontWeight: 500 }}>{hp.whyUsSection.reviewsBadge}</span>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section style={{ backgroundColor: config.brand.background }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <span className="inline-block px-4 py-1.5 rounded-full mb-4" style={{ backgroundColor: "rgba(199,32,42,0.1)", border: "1px solid rgba(199,32,42,0.28)", color: "#B11F2A", fontSize: "15px", fontWeight: 600, letterSpacing: "1px", textTransform: "uppercase" }}>
              {hp.testimonialsSection.badge}
            </span>
            <h2 className="m-0" style={{ fontFamily: config.brand.fonts.serif, fontSize: "clamp(32px, 3.9vw, 44px)", fontWeight: 700, color: config.brand.light }}>
              {hp.testimonialsSection.heading}
            </h2>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {testimonials.map((t, i) => (
              <motion.div
                key={t.name}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.1 }}
                className="p-7 rounded-2xl"
                style={{ backgroundColor: config.brand.white, border: `1px solid ${config.brand.border}` }}
              >
                <div className="flex gap-1 mb-4">
                  {[...Array(5)].map((_, j) => (
                    <Star key={j} size={16} fill={config.brand.starYellow} color={config.brand.starYellow} />
                  ))}
                </div>
                <p className="mb-5" style={{ fontSize: "16px", color: config.brand.light, lineHeight: 1.7, fontStyle: "italic" }}>
                  "{t.text}"
                </p>
                <div className="flex items-center gap-2">
                  <GoogleIcon sx={{ fontSize: 18, color: config.brand.primary }} />
                  <p className="m-0" style={{ fontSize: "15px", fontWeight: 600, color: config.brand.light }}>— {t.name}</p>
                </div>
              </motion.div>
            ))}
          </div>

          <div className="text-center mt-10">
            <a
              href={googleReviewsUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 no-underline transition-colors"
              style={{ fontSize: "16px", fontWeight: 600, color: config.brand.primary }}
            >
              {hp.testimonialsSection.viewAllLink}
              <ExternalLink size={16} />
            </a>
          </div>
        </div>
      </section>

      {/* About / Team */}
      <section style={{ backgroundColor: config.brand.white }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="order-2 lg:order-1 rounded-2xl overflow-hidden"
              style={{ boxShadow: "0 20px 60px rgba(0,0,0,0.1)" }}
            >
              <ImageWithFallback src={teamImg} alt="Construction team" className="w-full h-[400px] object-cover" />
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="order-1 lg:order-2"
            >
              <span className="inline-block px-4 py-1.5 rounded-full mb-4" style={{ backgroundColor: "rgba(199,32,42,0.1)", border: "1px solid rgba(199,32,42,0.28)", color: "#B11F2A", fontSize: "15px", fontWeight: 600, letterSpacing: "1px", textTransform: "uppercase" }}>
                {hp.teamSection.badge}
              </span>
              <h2 className="m-0 mb-5" style={{ fontFamily: config.brand.fonts.serif, fontSize: "clamp(32px, 3.9vw, 44px)", fontWeight: 700, color: config.brand.light, lineHeight: 1.2 }}>
                {hp.teamSection.heading}<br />
                <span style={{ color: config.brand.accent }}>{hp.teamSection.headingAccent}</span>
              </h2>
              <p className="mb-5" style={{ fontSize: "16px", color: config.brand.secondary, lineHeight: 1.8 }}>
                {hp.teamSection.body}
              </p>
              <div className="space-y-3 mb-8">
                {hp.whyUsSection.bullets.map((item) => (
                  <div key={item} className="flex items-center gap-3">
                    <CheckCircle2 size={18} style={{ color: config.brand.accent }} className="flex-shrink-0" />
                    <span style={{ fontSize: "15px", color: config.brand.text }}>{item}</span>
                  </div>
                ))}
              </div>
              <Link
                to="/contact"
                className="inline-flex items-center gap-2 px-7 py-3.5 no-underline rounded-xl transition-all duration-200 hover:scale-105"
                style={{ backgroundColor: config.brand.primary, color: "#FFFFFF", fontSize: "16px", fontWeight: 700 }}
              >
                <Phone size={18} />
                {hp.teamSection.cta}
              </Link>
            </motion.div>
          </div>
        </div>
      </section>

      {/* CTA Banner */}
      <section className="relative overflow-hidden" style={{ backgroundColor: config.brand.primary }}>
        <div className="absolute inset-0 opacity-10">
          <div className="absolute inset-0" style={{ backgroundImage: "radial-gradient(circle at 20% 50%, rgba(8,17,11,0.28) 0%, transparent 50%), radial-gradient(circle at 80% 50%, rgba(8,17,11,0.18) 0%, transparent 50%)" }} />
        </div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mx-auto max-w-5xl rounded-3xl px-8 py-10 sm:px-12 sm:py-12 text-center"
            style={{
              background: "linear-gradient(135deg, rgba(8,17,11,0.92) 0%, rgba(11,18,13,0.88) 100%)",
              border: "1px solid rgba(8,17,11,0.35)",
              boxShadow: "0 20px 50px rgba(8,17,11,0.22)",
            }}
          >
            <span
              className="inline-block px-4 py-1.5 rounded-full mb-5"
              style={{
                backgroundColor: "rgba(199,32,42,0.12)",
                border: "1px solid rgba(199,32,42,0.35)",
                color: "#FFEAF0",
                fontSize: "13px",
                fontWeight: 700,
                letterSpacing: "1px",
                textTransform: "uppercase",
              }}
            >
              {hp.ctaSection.heading}
            </span>
            <p
              className="m-0 mx-auto"
              style={{
                fontFamily: config.brand.fonts.serif,
                fontSize: "clamp(22px, 2.6vw, 32px)",
                fontWeight: 600,
                color: "#EEF7F0",
                maxWidth: "960px",
                lineHeight: 1.45,
                letterSpacing: "0.2px",
              }}
            >
              {hp.ctaSection.body}
            </p>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
