// STRUCTURE LOCKED — do not edit this file.
// To change colours/fonts edit src/site.theme.ts.
// To change text/links edit src/site.content.ts.
import { Outlet, Link, useLocation } from "react-router";
import { useEffect, useState } from "react";
import { Menu, X, Phone, Mail, MapPin, ArrowUp } from "lucide-react";
import { config } from "../config";

const navItems = config.nav;
const brandLogoSrc = config.logo;

export function Layout() {
  const location = useLocation();
  const [scrolled, setScrolled] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [showScrollTop, setShowScrollTop] = useState(false);

  useEffect(() => {
    window.scrollTo(0, 0);
    setMobileMenuOpen(false);
  }, [location.pathname]);

  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 20);
      setShowScrollTop(window.scrollY > 400);
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  return (
    <div className="min-h-screen flex flex-col" style={{ fontFamily: config.brand.fonts.sans }}>
      {/* Navbar */}
      <header
        className="w-full fixed top-0 left-0 right-0 z-50 transition-all duration-300"
        style={{
          backgroundColor: scrolled ? "rgba(255,255,255,0.96)" : "rgba(255,255,255,0.92)",
          backdropFilter: "blur(12px)",
          boxShadow: scrolled ? "0 1px 20px rgba(0,0,0,0.08)" : "none",
          borderBottom: "1px solid rgba(26,62,115,0.12)",
        }}
      >
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-[72px]">
            {/* Logo */}
            <Link to="/" className="flex items-center gap-3 no-underline group">
              <img
                src={brandLogoSrc}
                alt={`${config.business.name} logo`}
                className="h-11 w-auto transition-transform group-hover:scale-[1.02]"
              />
            </Link>

            {/* Desktop Nav */}
            <nav className="hidden lg:flex items-center gap-1">
              {navItems.map((item) => {
                const isActive = location.pathname === item.path;
                return (
                  <Link
                    key={item.path}
                    to={item.path}
                    className="no-underline px-3 py-2 rounded-lg transition-all duration-200"
                    style={{
                      fontSize: "16px",
                      fontWeight: isActive ? 600 : 500,
                      color: isActive ? config.brand.primary : config.brand.text,
                      backgroundColor: isActive ? config.brand.primaryAlpha08 : "transparent",
                    }}
                    onMouseEnter={(e) => {
                      if (!isActive) e.currentTarget.style.backgroundColor = config.brand.primaryAlpha08;
                    }}
                    onMouseLeave={(e) => {
                      if (!isActive) e.currentTarget.style.backgroundColor = "transparent";
                    }}
                  >
                    {item.label}
                  </Link>
                );
              })}
            </nav>

            {/* CTA + Mobile Toggle */}
            <div className="flex items-center gap-3">
              <Link
                to="/contact"
                className="hidden sm:inline-flex items-center gap-2 px-5 py-2.5 no-underline rounded-lg transition-all duration-200 hover:opacity-90"
                style={{ backgroundColor: config.brand.primary, color: "#FFFFFF", fontSize: "15px", fontWeight: 700 }}
              >
                <Phone size={15} />
                Free Quote
              </Link>
              <button
                onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
                className="lg:hidden p-2 rounded-lg border-none cursor-pointer transition-colors"
                style={{ backgroundColor: mobileMenuOpen ? config.brand.subtle : "transparent", color: config.brand.text }}
              >
                {mobileMenuOpen ? <X size={22} /> : <Menu size={22} />}
              </button>
            </div>
          </div>
        </div>

        {/* Mobile Menu */}
        {mobileMenuOpen && (
          <div className="lg:hidden px-4 pb-4" style={{ borderTop: `1px solid ${config.brand.subtle}` }}>
            <div className="flex flex-col gap-1 pt-2">
              {navItems.map((item) => {
                const isActive = location.pathname === item.path;
                return (
                  <Link
                    key={item.path}
                    to={item.path}
                    className="no-underline px-4 py-3 rounded-lg transition-colors"
                    style={{
                      fontSize: "16px",
                      fontWeight: isActive ? 600 : 500,
                      color: isActive ? config.brand.primary : config.brand.text,
                      backgroundColor: isActive ? config.brand.primaryAlpha08 : "transparent",
                    }}
                  >
                    {item.label}
                  </Link>
                );
              })}
              <Link
                to="/contact"
                className="mt-2 flex items-center justify-center gap-2 px-5 py-3 no-underline rounded-lg"
                style={{ backgroundColor: config.brand.primary, color: "#FFFFFF", fontSize: "16px", fontWeight: 700 }}
              >
                <Phone size={16} />
                Get a Free Quote
              </Link>
            </div>
          </div>
        )}
      </header>
      <div className="h-[72px]" />

      {/* Main Content */}
      <main className="flex-1">
        <Outlet />
      </main>

      {/* Footer */}
      <footer style={{ backgroundColor: config.brand.background }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-10">
            {/* Brand */}
            <div>
              <Link to="/" className="flex items-center gap-3 no-underline mb-5">
                <div
                  className="rounded-lg px-2 py-1"
                  style={{ backgroundColor: config.brand.white, border: `1px solid ${config.brand.border}` }}
                >
                  <img src={brandLogoSrc} alt={`${config.business.name} logo`} className="h-10 w-auto" />
                </div>
              </Link>
              <p style={{ fontSize: "15px", color: config.brand.secondary, lineHeight: 1.7 }}>
                {config.footer.tagline}
              </p>
            </div>

            {/* Contact */}
            <div>
              <h4 className="mb-4" style={{ color: config.brand.light, fontSize: "15px", fontWeight: 700, letterSpacing: "1px", textTransform: "uppercase" }}>
                Get in Touch
              </h4>
              <div className="flex flex-col gap-3">
                <a href={`tel:${config.business.phone}`} className="flex items-center gap-3 no-underline hover:opacity-80 transition-colors" style={{ fontSize: "15px", color: config.brand.secondary }}>
                  <Phone size={16} className="flex-shrink-0" style={{ color: config.brand.accent }} />
                  {config.business.phoneDisplay}
                </a>
                <a href={`mailto:${config.business.email}`} className="flex items-center gap-3 no-underline hover:opacity-80 transition-colors" style={{ fontSize: "15px", color: config.brand.secondary }}>
                  <Mail size={16} className="flex-shrink-0" style={{ color: config.brand.accent }} />
                  {config.business.email}
                </a>
                <div className="flex items-center gap-3" style={{ fontSize: "15px", color: config.brand.secondary }}>
                  <MapPin size={16} className="flex-shrink-0" style={{ color: config.brand.accent }} />
                  {config.business.location}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Bottom Bar */}
        <div style={{ borderTop: `1px solid ${config.brand.border}` }}>
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-5 flex flex-col sm:flex-row justify-between items-center gap-3">
            <p className="m-0" style={{ fontSize: "15px", color: config.brand.muted }}>
              &copy; {config.business.foundedYear} {config.business.nameFull}. All rights reserved.
            </p>
            <p className="m-0" style={{ fontSize: "14px", color: config.brand.muted }}>
              {config.business.location}
            </p>
          </div>
        </div>
      </footer>

      {/* Scroll to Top */}
      {showScrollTop && (
        <button
          onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
          className="fixed bottom-6 right-6 w-12 h-12 rounded-full flex items-center justify-center border-none cursor-pointer shadow-lg transition-all duration-300 hover:scale-110 z-50"
          style={{ backgroundColor: config.brand.primary, color: "#FFFFFF" }}
        >
          <ArrowUp size={20} />
        </button>
      )}
    </div>
  );
}
