// STRUCTURE LOCKED — do not edit this file.
// To change colours/fonts edit src/site.theme.ts.
// To change text edit src/site.content.ts.
import { motion } from "motion/react";
import { Briefcase, PoundSterling, MapPin, Users, ArrowRight, Mail, type LucideIcon } from "lucide-react";
import { config } from "../config";

const rp = config.recruitmentPage;

// Icon map for benefit icons — names match recruitmentPage.benefits[].icon in site.content.ts
const benefitIconMap: Record<string, LucideIcon> = {
  PoundSterling, Briefcase, Users, MapPin,
};

export function RecruitmentPage() {
  return (
    <div style={{ fontFamily: config.brand.fonts.sans }}>
      {/* Hero */}
      <section className="py-20" style={{ backgroundColor: config.brand.primary }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
            <span className="inline-block px-4 py-1.5 rounded-full mb-4" style={{ backgroundColor: "rgba(199,32,42,0.18)", color: "#FFEAF0", fontSize: "13px", fontWeight: 600, letterSpacing: "1px", textTransform: "uppercase" }}>
              {rp.badge}
            </span>
            <h1 className="m-0 mb-2 text-white" style={{ fontFamily: config.brand.fonts.serif, fontSize: "clamp(32px, 4vw, 50px)", fontWeight: 700, lineHeight: 1.15 }}>
              {rp.heading}
            </h1>
            <p className="m-0 mb-3" style={{ fontSize: "clamp(20px, 3vw, 32px)", color: "#FFFFFF", fontFamily: config.brand.fonts.serif, fontWeight: 600 }}>
              {rp.headingPL}
            </p>
            <div style={{ width: "48px", height: "2px", backgroundColor: config.brand.primary, marginBottom: "20px" }} />
            <p className="m-0 mb-1" style={{ fontSize: "16px", color: "#FFFFFF", maxWidth: "520px", lineHeight: 1.7 }}>
              {rp.intro}
            </p>
            <p className="m-0" style={{ fontSize: "14px", color: "#FFFFFF", maxWidth: "520px", lineHeight: 1.7 }}>
              {rp.introPL}
            </p>
          </motion.div>
        </div>
      </section>

      {/* Benefits */}
      <section style={{ backgroundColor: config.brand.primary }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {rp.benefits.map((b, i) => {
              const Icon = benefitIconMap[b.icon] ?? Briefcase;
              return (
                <motion.div
                  key={b.title}
                  initial={{ opacity: 0, y: 15 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1 }}
                  className="text-center"
                >
                  <Icon size={28} className="mx-auto mb-3" style={{ color: "rgba(244,248,255,0.94)" }} />
                  <h4 className="m-0 mb-0.5" style={{ color: "#F4F8FF", fontSize: "15px", fontWeight: 700 }}>{b.title}</h4>
                  <p className="m-0 mb-1" style={{ fontSize: "12px", color: "rgba(244,248,255,0.78)", fontStyle: "italic" }}>{b.titlePL}</p>
                  <p className="m-0 mb-0.5" style={{ fontSize: "13px", color: "rgba(244,248,255,0.88)" }}>{b.desc}</p>
                  <p className="m-0" style={{ fontSize: "11px", color: "rgba(244,248,255,0.72)", fontStyle: "italic" }}>{b.descPL}</p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Language badge + Positions */}
      <section style={{ backgroundColor: config.brand.background }}>
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-16 pb-4">
          <div className="flex items-center gap-3 mb-10">
            <span style={{ fontSize: "22px" }}>🇵🇱</span>
            <span style={{ fontSize: "13px", color: config.brand.secondary }}>
              {rp.languageBadge}
            </span>
          </div>

          <h2 className="m-0 mb-1 text-center" style={{ fontFamily: config.brand.fonts.serif, fontSize: "32px", fontWeight: 700, color: config.brand.light }}>
            {rp.openLabel}
          </h2>
          <p className="text-center mb-1" style={{ fontFamily: config.brand.fonts.serif, fontSize: "20px", fontWeight: 600, color: config.brand.muted }}>
            {rp.openLabelPL}
          </p>
          <p className="text-center mb-10" style={{ fontSize: "14px", color: config.brand.muted }}>
            {rp.locationNote}
          </p>

          <div className="space-y-4">
            {rp.roles.map((role, i) => (
              <motion.div
                key={role.title}
                initial={{ opacity: 0, y: 15 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.06 }}
                className="p-6 rounded-2xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 transition-all duration-200"
                style={{ backgroundColor: config.brand.white, border: `1px solid ${config.brand.border}` }}
                onMouseEnter={(e) => { e.currentTarget.style.boxShadow = "0 4px 20px rgba(0,0,0,0.06)"; e.currentTarget.style.borderColor = config.brand.primaryAlpha20; }}
                onMouseLeave={(e) => { e.currentTarget.style.boxShadow = "none"; e.currentTarget.style.borderColor = config.brand.border; }}
              >
                <div>
                  <h3 className="m-0 mb-0.5" style={{ fontSize: "16px", fontWeight: 700, color: config.brand.light }}>{role.title}</h3>
                  <p className="m-0 mb-2" style={{ fontSize: "13px", fontWeight: 500, color: config.brand.primary, fontStyle: "italic" }}>{role.titlePL}</p>
                  <p className="m-0 mb-0.5" style={{ fontSize: "13px", color: config.brand.secondary }}>{role.desc}</p>
                  <p className="m-0" style={{ fontSize: "12px", color: config.brand.muted, fontStyle: "italic" }}>{role.descPL}</p>
                </div>
                <div className="flex items-center gap-3 flex-shrink-0">
                  <span className="px-3 py-1 rounded-full" style={{ fontSize: "12px", fontWeight: 600, backgroundColor: "rgba(199,32,42,0.12)", color: "#B11F2A" }}>
                    {role.type}
                  </span>
                  <ArrowRight size={18} style={{ color: config.brand.muted }} />
                </div>
              </motion.div>
            ))}
          </div>

          {/* Apply */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mt-12 mb-16 text-center p-10 rounded-2xl"
            style={{ backgroundColor: config.brand.white, border: `1px solid ${config.brand.border}` }}
          >
            <Mail size={36} className="mx-auto mb-4" style={{ color: config.brand.accent }} />
            <h3 className="m-0 mb-1" style={{ fontSize: "20px", fontWeight: 700, color: config.brand.light }}>
              {rp.applyHeading}
            </h3>
            <p className="m-0 mb-4" style={{ fontSize: "15px", fontWeight: 600, color: config.brand.muted, fontStyle: "italic" }}>
              {rp.applyHeadingPL}
            </p>
            <p className="m-0 mb-1 mx-auto" style={{ fontSize: "14px", color: config.brand.secondary, maxWidth: "400px", lineHeight: 1.7 }}>
              {rp.applyBody}
            </p>
            <p className="m-0 mb-6 mx-auto" style={{ fontSize: "13px", color: config.brand.muted, maxWidth: "400px", lineHeight: 1.7, fontStyle: "italic" }}>
              {rp.applyBodyPL}
            </p>
            <a
              href={`mailto:${config.business.email}`}
              className="inline-flex items-center gap-2 px-7 py-3.5 no-underline rounded-xl transition-all duration-200 hover:scale-105"
              style={{ backgroundColor: config.brand.primary, color: "#FFFFFF", fontSize: "15px", fontWeight: 700 }}
            >
              <Mail size={18} />
              {config.business.email}
            </a>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
