// STRUCTURE LOCKED — do not edit this file.
// To change colours/fonts edit src/site.theme.ts.
// To change text/images edit src/site.content.ts and src/site.images.ts.
import { Link } from "react-router";
import { motion } from "motion/react";
import { Hammer, PaintBucket, Bath, Grid3X3, Wrench, Home, ArrowRight, Phone, type LucideIcon } from "lucide-react";
import { ImageWithFallback } from "./figma/ImageWithFallback";
import { config } from "../config";

const serviceIconMap: Record<string, LucideIcon> = {
  hammer: Hammer, paintBucket: PaintBucket, bath: Bath,
  grid: Grid3X3, wrench: Wrench, home: Home,
};

// Service images ordered to match config.services (builders, painters, bathrooms, tilers, joiners, extensions)
const serviceImageSlots = [
  config.images.builders,
  config.images.painters,
  config.images.bathrooms,
  config.images.tilers,
  config.images.joiners,
  config.images.extensions,
];

const services = config.services.map((s, i) => ({
  ...s,
  Icon:  serviceIconMap[s.icon] ?? Hammer,
  image: serviceImageSlots[i],
}));

const sp = config.servicesPage;

export function ServicesPage() {
  return (
    <div style={{ fontFamily: config.brand.fonts.sans }}>
      {/* Hero */}
      <section className="py-14 sm:py-20" style={{ backgroundColor: config.brand.primary }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="text-center">
            <span className="inline-block px-3 py-1 sm:px-4 sm:py-1.5 rounded-full mb-3 sm:mb-4" style={{ backgroundColor: "rgba(199,32,42,0.18)", border: "1px solid rgba(199,32,42,0.45)", color: "#FFEAF0", fontSize: "clamp(11px, 2.8vw, 15px)", fontWeight: 600, letterSpacing: "0.8px", textTransform: "uppercase" }}>
              {sp.badge}
            </span>
            <h1 className="m-0 mb-4 text-white" style={{ fontFamily: config.brand.fonts.serif, fontSize: "clamp(36px, 4.6vw, 58px)", fontWeight: 700, lineHeight: 1.15, letterSpacing: "-0.5px" }}>
              {sp.heading.split("\n").map((line, i) => (
                <span key={i}>{line}{i < sp.heading.split("\n").length - 1 && <br />}</span>
              ))}
            </h1>
            <p className="m-0 mx-auto" style={{ fontSize: "17px", color: "#FFFFFF", maxWidth: "620px", lineHeight: 1.7 }}>
              {sp.intro}
            </p>
          </motion.div>
        </div>
      </section>

      {/* Services Grid */}
      <section style={{ backgroundColor: config.brand.background }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-14 sm:py-20">
          <div className="space-y-20">
            {services.map((service, i) => (
              <motion.div
                key={service.title}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5 }}
                className={`grid grid-cols-1 lg:grid-cols-2 gap-12 items-center ${i % 2 === 1 ? "lg:[direction:rtl]" : ""}`}
              >
                <div className={i % 2 === 1 ? "lg:[direction:ltr]" : ""}>
                  <div className="w-14 h-14 rounded-2xl flex items-center justify-center mb-5" style={{ backgroundColor: "rgba(199,32,42,0.10)" }}>
                    <service.Icon size={26} style={{ color: config.brand.accent }} />
                  </div>
                  <h2 className="m-0 mb-4" style={{ fontFamily: config.brand.fonts.serif, fontSize: "28px", fontWeight: 700, color: config.brand.light }}>
                    {service.title}
                  </h2>
                  <p className="mb-6" style={{ fontSize: "16px", color: config.brand.secondary, lineHeight: 1.8 }}>
                    {service.description}
                  </p>
                  <Link
                    to="/contact"
                    className="inline-flex items-center gap-2 no-underline"
                    style={{ fontSize: "15px", fontWeight: 600, color: config.brand.primary }}
                  >
                    {sp.quoteLink} <ArrowRight size={15} />
                  </Link>
                </div>
                <div className={`rounded-2xl overflow-hidden ${i % 2 === 1 ? "lg:[direction:ltr]" : ""}`} style={{ boxShadow: "0 12px 40px rgba(0,0,0,0.1)" }}>
                  <ImageWithFallback src={service.image} alt={service.title} className="w-full h-[300px] object-cover" />
                </div>
              </motion.div>
            ))}
          </div>

          {/* CTA */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mt-20 text-center p-12 rounded-2xl"
            style={{ backgroundColor: config.brand.primary }}
          >
            <h3 className="m-0 mb-3" style={{ color: "#F4F8FF", fontFamily: config.brand.fonts.serif, fontSize: "28px", fontWeight: 700 }}>
              {sp.ctaHeading}
            </h3>
            <p className="m-0 mb-6 mx-auto" style={{ fontSize: "16px", color: "rgba(244,248,255,0.88)", maxWidth: "450px", lineHeight: 1.7 }}>
              {sp.ctaBody}
            </p>
            <Link
              to="/contact"
              className="inline-flex items-center gap-2 px-7 py-3.5 no-underline rounded-xl transition-all duration-200 hover:scale-105"
              style={{ backgroundColor: config.brand.primary, color: "#FFFFFF", fontSize: "16px", fontWeight: 700 }}
            >
              <Phone size={18} />
              {sp.ctaBtn}
            </Link>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
