// STRUCTURE LOCKED — do not edit this file.
// To change colours/fonts edit src/site.theme.ts.
// To change text edit src/site.content.ts.
import { motion } from "motion/react";
import { Star, Quote } from "lucide-react";
import GoogleIcon from "@mui/icons-material/Google";
import { config } from "../config";

const testimonials = config.testimonials;
const tp = config.testimonialsPage;

export function TestimonialsPage() {
  return (
    <div style={{ fontFamily: config.brand.fonts.sans }}>
      {/* Hero */}
      <section className="py-20" style={{ backgroundColor: config.brand.primary }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center">
            <span className="inline-block px-4 py-1.5 rounded-full mb-4" style={{ backgroundColor: "rgba(199,32,42,0.18)", color: "#FFEAF0", fontSize: "15px", fontWeight: 600, letterSpacing: "1px", textTransform: "uppercase" }}>
              {tp.badge}
            </span>
            <h1 className="m-0 mb-4 text-white" style={{ fontFamily: config.brand.fonts.serif, fontSize: "clamp(36px, 4.6vw, 58px)", fontWeight: 700 }}>
              {tp.heading}
            </h1>
            <p className="m-0 mx-auto" style={{ fontSize: "17px", color: "#FFFFFF", maxWidth: "520px", lineHeight: 1.7 }}>
              {tp.intro}
            </p>

            {/* Rating Summary */}
            <div className="flex items-center justify-center gap-3 mt-8">
              <div className="flex gap-1">
                {[...Array(5)].map((_, i) => <Star key={i} size={24} fill={config.brand.starYellow} color={config.brand.starYellow} />)}
              </div>
              <span className="text-white" style={{ fontSize: "20px", fontWeight: 700 }}>{tp.ratingValue}</span>
              <span style={{ fontSize: "15px", color: "#FFFFFF" }}>{tp.ratingLabel}</span>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Testimonials Grid */}
      <section style={{ backgroundColor: config.brand.background }}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {testimonials.map((t, i) => (
              <motion.div
                key={t.name}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.06 }}
                className="p-7 rounded-2xl flex flex-col"
                style={{ backgroundColor: config.brand.white, border: `1px solid ${config.brand.border}` }}
              >
                <Quote size={28} style={{ color: config.brand.primaryAlpha15 }} className="mb-3" />
                <div className="flex gap-1 mb-4">
                  {[...Array(5)].map((_, j) => <Star key={j} size={14} fill={config.brand.starYellow} color={config.brand.starYellow} />)}
                </div>
                <p className="mb-5 flex-1" style={{ fontSize: "15px", color: config.brand.secondary, lineHeight: 1.7, fontStyle: "italic" }}>
                  "{t.text}"
                </p>
                <div className="pt-4" style={{ borderTop: `1px solid ${config.brand.subtle}` }}>
                  <div className="flex items-center gap-2">
                    <GoogleIcon sx={{ fontSize: 18, color: config.brand.primary }} />
                    <p className="m-0" style={{ fontSize: "15px", fontWeight: 700, color: config.brand.light }}>{t.name}</p>
                  </div>
                  <p className="m-0" style={{ fontSize: "14px", color: config.brand.muted }}>{t.location}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
